### ISSUE TITLE
Rendezvous idea: beacon system

### ISSUE THREAD

**Issue by enkait** [mibpl/StreetViewGame#76]
This is an idea to help fix #58 in a slightly more interactive way.
The problem is that people who already arrived have nothing to do, and even moving is dangerous because coming back might be hard.
The first idea is that when two players meet they can create a beacon (through an interface of: clicking a "make beacon button" underneath the map, and then clicking on the marker map at the location where you are). The beacon has a randomly chosen radius (maybe instead of random we could let players control it). The beacon adds a few gameplay elements:
1. The beacon gets added to everyones marker maps. Anyone who's ever close to the beacon gets the ability to teleport back to it (by clicking on its marker in the map). This makes it much less risky to go on an adventure.
2. Anyone who's within the radius gets feedback that they're in range. This means that players can help other players by setting up beacons.
After you set up a beacon, you're free to go setup more beacons. However, to make it more challenging, I would restrict where these "extra" beacons can be placed only to points of interest obtained from the maps API (I hope POIs are available in some form). This means when a player arrives at the meetup point, a good strategy for them is to help others by navigating them, then set up a beacon whenever someone arrives, and finally decide together (taking into account both how dificult it will be to get somewhere, and also potential usefulness to players who haven't yet arrived) on another beacon and set out to go there.

**Comment by enkait** [comment]
@anula @mibpl Thoughts?

**Comment by mibpl** [comment]
Approved for testing on humans.

Concern: ppl leaving the meetup point will still prolong the game.
Suggestion: change the win condition as well.

**Comment by enkait** [comment]
It won't prolong the game IMO, because they can teleport back to it at any time. Or am I misunderstanding you?

A second thought: perhaps we should make the beacon size depend on the players, e.g. make it reach always to the median of players who aren't within 50m of it. This would make the beacon always have some players inside and some outside, and may be an easy way to make the beacons reasonably helpful (the idea here is that the beacon is only really helpful to people who are on the boundary).
